### ISSUE TITLE
how to get trinity.fasta and trinity-swissprot-pep.fasta?

### ISSUE THREAD

**Issue by lijing28101** [eswlab/orphan-prediction#4]
Hi, I'm trying to run this pipeline on yeast.
How can I get `trinity.fasta` and `trinity-swissprot-pep.fasta`? 
There are sever trinity relative scripts. I have no idea which one I need to use.

**Comment by aseetharam** [comment]
For running trinity, depending on the dataset, you can use either:
`runTrinityS.sh` (single-end reads only) or `runTrinity.sh` (for paired-end reads) or `runTrinity-gg.sh` (genome-guided). After translating Trinity transcripts to obtain peptide, and merging it with Swissport downloaded proteins (closely related), you get `trinity-swissprot-pep.fasta`
