### ISSUE TITLE
question for maker_process.sh

### ISSUE THREAD

**Issue by lijing28101** [eswlab/orphan-prediction#5]
When map first round transcritps to genome using GMAP, 
```
gmap   \
   -d TAIR10 \
   -D /work/LAS/mash-lab/arnstrm/20170320_ArabidopsosGenePrediction_as/04_maker/common_files \
   -t 16 \
   -B 5 \
   -A -f samse \
   --input-buffer-size=10000000 \
   --output-buffer-size=10000000 \
     ${MAKERDIR}.all.maker.transcripts.fasta > ${MAKERDIR}_se.sam
```
How to make the genome database `TAIR10`?
And what's the `-D /work/LAS/mash-lab/arnstrm/20170320_ArabidopsosGenePrediction_as/04_maker/common_files`?
Is this a directory for `TAIR10`? Or something else in this directory are used as input?

**Comment by aseetharam** [comment]
the `gmap` uses `-D` to locate the directory where the index files are located and `-d` for the name of index. You can generate index using 
```
DB=/path/to/index/location
FASTA=genome.fasta
gmap_build -d ${FASTA%.*} -D ${DB} ${FASTA}
```
