### ISSUE TITLE
Unable to download one of the scripts for phylo-stratification step

### ISSUE THREAD

**Issue by anandksrao** [eswlab/orphan-prediction#6]
Greetings!

For executing the steps explained under [Run phylostratr to infer phylostrata of genes, and identify orphan genes](https://github.com/eswlab/orphan-prediction/blob/305c2486141ac8ea48441a5ae0ff262c736b21fa/README.md#run-phylostratr-to-infer-phylostrata-of-genes-and-identify-orphan-genes).  

I am unable to download [runPhylostrarRa.sh ](https://github.com/eswlab/orphan-prediction/blob/305c2486141ac8ea48441a5ae0ff262c736b21fa/scripts/runPhylostratR.sh). 
That link is dead ?

OR is that a typo, that should in reality link to the script named [runPhylostratRb.sh](https://github.com/eswlab/orphan-prediction/blob/305c2486141ac8ea48441a5ae0ff262c736b21fa/scripts/runPhylostratRb.sh
) , that is available for download?

Could you please help / clarify? Thank you!

**Comment by aseetharam** [comment]
Thank you, @anandksrao to bringing this to our attention. I've fixed the path for the scripts in the master branch.
Please check the [link](https://github.com/eswlab/orphan-prediction/blob/master/README.md#run-phylostratr-to-infer-phylostrata-of-genes-and-identify-orphan-genes) again!
